version: '3.5'

networks:
  mashreqnetwork:
    driver: bridge

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mashreq
      POSTGRES_PASSWORD: HaaeN9TZ5ssmYWpSm3nu
      POSTGRES_DB: mashreq
