version: '3.5'

networks:
  mashreqnetwork:
    driver: bridge

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mashreq
      POSTGRES_PASSWORD: HaaeN9TZ5ssmYWpSm3nu
      POSTGRES_DB: mashreq

  api:
    image: ajhelsby/mashreq-coding-test
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOSTNAME: localhost
      DATABASE_USERNAME: mashreq
      DATABASE_PASSWORD: HaaeN9TZ5ssmYWpSm3nu
      DATABASE_NAME: mashreq
      JWT_SECRET: 7110BFEFB081550D9656FFE04C894FE7
      OPENAPI_USERNAME: openapi
      OPENAPI_PASSWORD: openapi