name: Run Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    permissions:
      contents: write # for google-github-actions/release-please-action to create release commit
      pull-requests: write # for google-github-actions/release-please-action to create release PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '22'
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{secrets.RELEASE_PLEASE_TOKEN}}

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      release_tag_name: ${{ steps.release.outputs.tag_name }}
